---
title: "Odds in Risk"
author: "Timothy Adams"
date: "August 14, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

roll <- function(dice = 1, times = 1) {
  sample(1:6, size = dice, replace = TRUE)
}

# Get the top two of the three offensive rolls.
# Largest one is the first in the vector.
get_top_two <- function(roll) {
  n <- length(roll)
  
  if (length(roll) < 2)
  {
    return(roll)
  }
  sorted <- sort(roll, partial = n-1)
  c(sorted[n], sorted[n-1])
}

# compare each pair of dice. Defense wins ties.
compare <- function(attack, defense) {
  if(attack > defense){
    return("attack")
  }
  else return("defense")
}

# one dice roll from both defense and offense.
battle <- function(num_d = 2, num_o = 3) {
  d <- roll(num_d)
  d_top <- sort(d, decreasing = TRUE) # get highest defensive roll in index 1
  o <- roll(num_o)
  o_top <- get_top_two(o)
  
  if(min(num_d, num_o) == 1){
    obv <- compare(o_top[1], d_top[1])
  }
  else {
    obv <- c(compare(o_top[1], d_top[1]), compare(o_top[2], d_top[2]))
  }
  
  obv
}

sim <- function(n, num_d, num_o) {
  replicate(n, battle(num_d = num_d, num_o = num_o))
}

# probability the attacker wins
prob_attacker(result) {
  length(result[result == "attack"])/length(result)
}


```


With 3 dice for the attacker and 2 for the defender:

```{r}
result <- sim(100000, num_d = 2, num_o = 3)

# probability the attacker wins
prob_attacker(result)
```


With 2 dice for both:

```{r}
result <- sim(100000, num_d = 2, num_o = 2)

# probability the attacker wins
prob_attacker(result)
```

What happens if the defender uses one die?

```{r}
attack3 <- sim(100000, num_d = 1, num_o = 3)

# probability the attacker wins (with 3 dice)
prob_attacker(attack3)

attack2 <- sim(100000, num_d = 1, num_o = 2)

# probability the attacker wins (with 2 dice)
prob_attacker(attack2)

attack1 <- sim(100000, num_d = 1, num_o = 1)

# probability the attacker wins (with 1 dice)
prob_attacker(attack1)


```
